name: ui_kit
description: Chirp UI kit — design system widgets, themes, icons
publish_to: 'none'
version: 0.1.0
resolution: workspace

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_gen:
  output: lib/gen/
  line_length: 80
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      package_parameter_enabled: true
