import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:qa_tools_flutter/src/debug_log_store.dart';
import 'package:qa_tools_flutter/src/view/flutter_lens_theme.dart';
import 'package:qa_tools_flutter/src/view/debug_tools_panel_styles.dart';

/// DebugLogsViewer is a widget that displays a list of logs.
/// Allows for the inspection of log messages generated by the application.
class DebugLogsViewer extends StatefulWidget {
  const DebugLogsViewer({
    super.key,
    required this.onTap,
  });

  final VoidCallback onTap;

  @override
  State<DebugLogsViewer> createState() => _DebugLogsViewerState();
}

class _DebugLogsViewerState extends State<DebugLogsViewer> {
  _LogFilter _selectedFilter = _LogFilter.all;

  @override
  Widget build(BuildContext context) {
    return Theme(
      data: flutterLensTheme(context),
      child: Scaffold(
        backgroundColor: DebugToolsPanelStyles.sheetFill,
        body: SafeArea(
          child: Column(
            children: [
              Row(
                children: [
                  const Padding(
                    padding: EdgeInsets.symmetric(horizontal: 16, vertical: 16),
                    child: Text(
                      'Debug Logs',
                      style: TextStyle(
                        fontSize: 14,
                        fontWeight: FontWeight.w800,
                        letterSpacing: -0.2,
                        color: DebugToolsPanelStyles.textPrimary,
                        fontFamily: flutterLensFontFamily,
                      ),
                    ),
                  ),
                  const Spacer(),
                  _HeaderButton(
                    icon: Icons.clear_rounded,
                    onTap: widget.onTap,
                  ),
                  const SizedBox(width: 8),
                  _HeaderButton(
                    icon: Icons.delete_outline_rounded,
                    onTap: DebugLogStore.instance.clear,
                  ),
                  const SizedBox(width: 16),
                ],
              ),
              SizedBox(
                height: 38,
                child: ListView.separated(
                  padding: const EdgeInsets.fromLTRB(16, 8, 16, 4),
                  scrollDirection: Axis.horizontal,
                  itemCount: _LogFilter.values.length,
                  separatorBuilder: (context, index) => const SizedBox(width: 8),
                  itemBuilder: (context, index) {
                    final filter = _LogFilter.values[index];
                    final isSelected = filter == _selectedFilter;
                    return _FilterChip(
                      filter: filter,
                      title: _filterTitle(filter),
                      isSelected: isSelected,
                      onTap: () => setState(() => _selectedFilter = filter),
                    );
                  },
                ),
              ),
              Expanded(
                child: Padding(
                  padding: const EdgeInsets.fromLTRB(16, 12, 16, 16),
                  child: DecoratedBox(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(24),
                      boxShadow: const [
                        BoxShadow(
                          color: Color(0x66000000),
                          blurRadius: 32,
                          offset: Offset(0, 16),
                        ),
                      ],
                    ),
                    child: ClipRRect(
                      borderRadius: BorderRadius.circular(24),
                      child: DecoratedBox(
                        decoration: BoxDecoration(
                          borderRadius: BorderRadius.circular(24),
                          color: DebugToolsPanelStyles.sheetFill,
                          border: Border.all(color: Colors.white.withValues(alpha: 0.08)),
                        ),
                        child: ValueListenableBuilder<List<DebugLogEntry>>(
                          valueListenable: DebugLogStore.instance.logs,
                          builder: (context, logs, _) {
                            final filteredLogs = _filterLogs(logs);

                            if (logs.isEmpty) {
                              return const Center(
                                child: Padding(
                                  padding: EdgeInsets.symmetric(horizontal: 24),
                                  child: Text(
                                    'No logs captured yet.\nStart interacting with the app to see logs here.',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      fontSize: 13,
                                      height: 1.45,
                                      color: Color(0xA3FFFFFF),
                                      fontFamily: flutterLensFontFamily,
                                    ),
                                  ),
                                ),
                              );
                            }

                            if (filteredLogs.isEmpty) {
                              return Center(
                                child: Padding(
                                  padding: const EdgeInsets.symmetric(horizontal: 24),
                                  child: Text(
                                    'No ${_filterTitle(_selectedFilter).toLowerCase()} logs yet.',
                                    textAlign: TextAlign.center,
                                    style: const TextStyle(
                                      fontSize: 13,
                                      height: 1.45,
                                      color: Color(0xA3FFFFFF),
                                      fontFamily: flutterLensFontFamily,
                                    ),
                                  ),
                                ),
                              );
                            }

                            return ListView.separated(
                              padding: const EdgeInsets.only(top: 6, bottom: 10),
                              itemCount: filteredLogs.length,
                              separatorBuilder: (context, index) {
                                return Padding(
                                  padding: const EdgeInsets.only(left: 56, right: 16),
                                  child: Divider(
                                    height: 1,
                                    color: Colors.white.withValues(alpha: 0.04),
                                  ),
                                );
                              },
                              itemBuilder: (context, index) {
                                final entry = filteredLogs[filteredLogs.length - 1 - index];
                                final level = entry.level;
                                final levelTitle = _getLevelTitle(level);
                                final logText = '[${_formatTime(entry.timestamp)}] $levelTitle: ${entry.message}';

                                return Material(
                                  color: Colors.transparent,
                                  child: InkWell(
                                    onTap: () async {
                                      await Clipboard.setData(ClipboardData(text: logText));
                                      if (!context.mounted) return;
                                      final messenger = ScaffoldMessenger.maybeOf(context);
                                      if (messenger == null) return;
                                      messenger
                                        ..hideCurrentSnackBar()
                                        ..showSnackBar(
                                          const SnackBar(
                                            content: Text('Log copied to clipboard'),
                                            duration: Duration(milliseconds: 1200),
                                          ),
                                        );
                                    },
                                    child: Padding(
                                      padding: const EdgeInsets.fromLTRB(14, 12, 14, 12),
                                      child: Row(
                                        crossAxisAlignment: CrossAxisAlignment.start,
                                        children: [
                                          _LevelBadge(level: level),
                                          const SizedBox(width: 12),
                                          Expanded(
                                            child: Column(
                                              crossAxisAlignment: CrossAxisAlignment.start,
                                              children: [
                                                Row(
                                                  children: [
                                                    Expanded(
                                                      child: Text(
                                                        levelTitle,
                                                        maxLines: 1,
                                                        overflow: TextOverflow.ellipsis,
                                                        style: TextStyle(
                                                          fontSize: 8,
                                                          fontWeight: FontWeight.w900,
                                                          letterSpacing: 0.9,
                                                          color: _getMetaColor(level),
                                                          fontFamily: flutterLensFontFamily,
                                                          fontFeatures: const [
                                                            FontFeature.tabularFigures(),
                                                          ],
                                                        ),
                                                      ),
                                                    ),
                                                    const SizedBox(width: 8),
                                                    Text(
                                                      _formatTime(entry.timestamp),
                                                      style: TextStyle(
                                                        fontSize: 8,
                                                        fontWeight: FontWeight.w900,
                                                        color: Colors.white.withValues(alpha: 0.28),
                                                        fontFamily: flutterLensFontFamily,
                                                        fontFeatures: const [
                                                          FontFeature.tabularFigures(),
                                                        ],
                                                      ),
                                                    ),
                                                  ],
                                                ),
                                                const SizedBox(height: 6),
                                                Text(
                                                  entry.message,
                                                  style: TextStyle(
                                                    fontSize: 10,
                                                    color: _getMessageColor(level),
                                                    fontFamily: flutterLensFontFamily,
                                                    fontFeatures: const [
                                                      FontFeature.tabularFigures(),
                                                    ],
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ),
                                        ],
                                      ),
                                    ),
                                  ),
                                );
                              },
                            );
                          },
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Color _getMetaColor(DebugLogLevel level) {
    switch (level) {
      case DebugLogLevel.error:
        return const Color(0xCCEF4444);
      case DebugLogLevel.warning:
        return const Color(0xCCF7A250);
      case DebugLogLevel.debug:
      case DebugLogLevel.verbose:
      case DebugLogLevel.info:
        return Colors.white.withValues(alpha: 0.40);
    }
  }

  Color _getMessageColor(DebugLogLevel level) {
    switch (level) {
      case DebugLogLevel.error:
        return const Color(0xFFEF4444);
      case DebugLogLevel.warning:
        return const Color(0xFFF7A250);
      case DebugLogLevel.debug:
      case DebugLogLevel.verbose:
      case DebugLogLevel.info:
        return Colors.white.withValues(alpha: 0.90);
    }
  }

  String _getLevelTitle(DebugLogLevel level) {
    switch (level) {
      case DebugLogLevel.error:
        return 'ERROR';
      case DebugLogLevel.warning:
        return 'WARNING';
      case DebugLogLevel.debug:
        return 'DEBUG';
      case DebugLogLevel.verbose:
        return 'VERBOSE';
      case DebugLogLevel.info:
        return 'INFO';
    }
  }

  String _formatTime(DateTime timestamp) {
    final hour = timestamp.hour.toString().padLeft(2, '0');
    final minute = timestamp.minute.toString().padLeft(2, '0');
    final second = timestamp.second.toString().padLeft(2, '0');
    final centisecond = (timestamp.millisecond ~/ 10).toString().padLeft(2, '0');
    return '$hour:$minute:$second.$centisecond';
  }

  List<DebugLogEntry> _filterLogs(List<DebugLogEntry> logs) {
    if (_selectedFilter == _LogFilter.all) {
      return logs;
    }

    return logs.where((entry) {
      switch (_selectedFilter) {
        case _LogFilter.all:
          return true;
        case _LogFilter.info:
          return entry.level == DebugLogLevel.info;
        case _LogFilter.warning:
          return entry.level == DebugLogLevel.warning;
        case _LogFilter.error:
          return entry.level == DebugLogLevel.error;
        case _LogFilter.debug:
          return entry.level == DebugLogLevel.debug || entry.level == DebugLogLevel.verbose;
      }
    }).toList();
  }

  String _filterTitle(_LogFilter filter) {
    switch (filter) {
      case _LogFilter.all:
        return 'All';
      case _LogFilter.info:
        return 'Info';
      case _LogFilter.warning:
        return 'Warn';
      case _LogFilter.error:
        return 'Error';
      case _LogFilter.debug:
        return 'Debug';
    }
  }
}

enum _LogFilter { all, info, warning, error, debug }

class _HeaderButton extends StatelessWidget {
  const _HeaderButton({
    required this.icon,
    required this.onTap,
  });

  final IconData icon;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.white.withValues(alpha: 0.04),
      shape: const CircleBorder(),
      child: InkWell(
        customBorder: const CircleBorder(),
        onTap: onTap,
        child: Container(
          width: 34,
          height: 34,
          decoration: BoxDecoration(
            shape: BoxShape.circle,
            border: Border.all(color: Colors.white.withValues(alpha: 0.08)),
          ),
          child: Icon(icon, size: 18, color: DebugToolsPanelStyles.textPrimary.withValues(alpha: 0.45)),
        ),
      ),
    );
  }
}

class _FilterChip extends StatelessWidget {
  const _FilterChip({
    required this.filter,
    required this.title,
    required this.isSelected,
    required this.onTap,
  });

  final _LogFilter filter;
  final String title;
  final bool isSelected;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return Material(
      color: Colors.transparent,
      child: InkWell(
        borderRadius: BorderRadius.circular(999),
        onTap: onTap,
        child: Ink(
          padding: const EdgeInsets.symmetric(horizontal: 12),
          decoration: BoxDecoration(
            borderRadius: BorderRadius.circular(999),
            border: Border.all(
              color: isSelected ? _selectedBorderColor(filter) : Colors.white.withValues(alpha: 0.10),
            ),
            gradient: isSelected ? _selectedGradient(filter) : null,
            color: isSelected ? null : Colors.white.withValues(alpha: 0.04),
          ),
          child: Center(
            child: Text(
              title.toUpperCase(),
              style: TextStyle(
                fontSize: 8,
                fontWeight: FontWeight.w900,
                letterSpacing: 0.9,
                color:
                    isSelected ? _selectedTextColor(filter) : DebugToolsPanelStyles.textPrimary.withValues(alpha: 0.45),
                fontFamily: flutterLensFontFamily,
                fontFeatures: const [
                  FontFeature.tabularFigures(),
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }

  Gradient _selectedGradient(_LogFilter value) {
    switch (value) {
      case _LogFilter.warning:
        return const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            Color(0x33F7A250),
            Color(0x11F7A250),
          ],
        );
      case _LogFilter.error:
        return const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            Color(0x33EF4444),
            Color(0x11EF4444),
          ],
        );
      case _LogFilter.info:
        return const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            Color(0x334ADE80),
            Color(0x114ADE80),
          ],
        );
      case _LogFilter.debug:
      case _LogFilter.all:
        return const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [Color(0xFFF7A250), Color(0xFFE24A79), Color(0xFF5A3386)],
        );
    }
  }

  Color _selectedBorderColor(_LogFilter value) {
    switch (value) {
      case _LogFilter.warning:
        return const Color(0x66F7A250);
      case _LogFilter.error:
        return const Color(0x66EF4444);
      case _LogFilter.info:
        return const Color(0x664ADE80);
      case _LogFilter.debug:
      case _LogFilter.all:
        return Colors.transparent;
    }
  }

  Color _selectedTextColor(_LogFilter value) {
    switch (value) {
      case _LogFilter.warning:
        return const Color(0xFFF7A250);
      case _LogFilter.error:
        return const Color(0xFFEF4444);
      case _LogFilter.info:
        return const Color(0xFF4ADE80);
      case _LogFilter.debug:
      case _LogFilter.all:
        return Colors.white.withValues(alpha: 0.98);
    }
  }
}

class _LevelBadge extends StatelessWidget {
  const _LevelBadge({required this.level});

  final DebugLogLevel level;

  @override
  Widget build(BuildContext context) {
    final label = _label(level);

    if (level == DebugLogLevel.debug || level == DebugLogLevel.verbose) {
      return Container(
        width: 24,
        height: 24,
        decoration: const BoxDecoration(
          shape: BoxShape.circle,
          gradient: DebugToolsPanelStyles.accentGradient,
        ),
        child: Center(
          child: Text(
            label,
            style: const TextStyle(
              color: Colors.white,
              fontWeight: FontWeight.w900,
              fontSize: 11,
              fontFamily: flutterLensFontFamily,
            ),
          ),
        ),
      );
    }

    return Container(
      width: 24,
      height: 24,
      alignment: Alignment.center,
      decoration: BoxDecoration(
        shape: BoxShape.circle,
        gradient: _fillGradient(level),
        border: Border.all(color: _borderColor(level)),
      ),
      child: Text(
        label,
        style: TextStyle(
          color: _textColor(level),
          fontWeight: FontWeight.w800,
          fontSize: 11,
          fontFamily: flutterLensFontFamily,
        ),
      ),
    );
  }

  String _label(DebugLogLevel value) {
    switch (value) {
      case DebugLogLevel.warning:
        return 'W';
      case DebugLogLevel.error:
        return 'E';
      case DebugLogLevel.info:
        return 'I';
      case DebugLogLevel.debug:
      case DebugLogLevel.verbose:
        return 'D';
    }
  }

  Gradient _fillGradient(DebugLogLevel value) {
    switch (value) {
      case DebugLogLevel.warning:
        return const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            Color(0x33F7A250),
            Color(0x11F7A250),
          ],
        );
      case DebugLogLevel.error:
        return const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            Color(0x33EF4444),
            Color(0x11EF4444),
          ],
        );
      case DebugLogLevel.info:
        return const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            Color(0x334ADE80),
            Color(0x114ADE80),
          ],
        );
      case DebugLogLevel.debug:
      case DebugLogLevel.verbose:
        return const LinearGradient(
          begin: Alignment.topLeft,
          end: Alignment.bottomRight,
          colors: [
            Colors.transparent,
            Colors.transparent,
          ],
        );
    }
  }

  Color _borderColor(DebugLogLevel value) {
    switch (value) {
      case DebugLogLevel.warning:
        return const Color(0x66F7A250);
      case DebugLogLevel.error:
        return const Color(0x66EF4444);
      case DebugLogLevel.info:
        return const Color(0x664ADE80);
      case DebugLogLevel.debug:
      case DebugLogLevel.verbose:
        return Colors.transparent;
    }
  }

  Color _textColor(DebugLogLevel value) {
    switch (value) {
      case DebugLogLevel.warning:
        return const Color(0xFFF7A250);
      case DebugLogLevel.error:
        return const Color(0xFFEF4444);
      case DebugLogLevel.info:
        return const Color(0xFF4ADE80);
      case DebugLogLevel.debug:
      case DebugLogLevel.verbose:
        return Colors.white;
    }
  }
}
